### ISSUE TITLE
Update Website Logo

### ISSUE THREAD

**Issue by its-aye-lisa** [SupplyChainSandbox/supplychainsandbox.github.io#14]
- [ ] Decide if we want a new logo
 - [ ] Pick new logo

Need to decide if we are going to go with a  new logo since that will impact the design of the website.

**Comment by its-aye-lisa** [comment]
@TypeIsCheap I started putting together an [idea generation document](https://docs.google.com/presentation/d/1d3eekySHAA2FZJh4iC5OBsWdVnBfyHhN_YPC23wVsjI/edit#slide=id.p)

**Comment by TypeIsCheap** [comment]
@its-a-lisa can you add typeischeap@gmail.com to the document access list? Thanks!

**Comment by TypeIsCheap** [comment]
"Paid" logo options here: https://docs.google.com/presentation/d/1PCfZ0r4h191AQfHyKHhJctDWkPP5LnrEJ9n2x-tR2xM/edit#slide=id.gbaf1beb5ca_0_0

A couple of early prototypes of original ideas here (I like the conveyor belt): https://docs.google.com/presentation/d/1PCfZ0r4h191AQfHyKHhJctDWkPP5LnrEJ9n2x-tR2xM/edit#slide=id.gbba386a79b_0_11

Should we add @beauwoods to this issue?
