### ISSUE TITLE
Website information architecture

### ISSUE THREAD

**Issue by its-aye-lisa** [SupplyChainSandbox/supplychainsandbox.github.io#6]
- [x] start the thing
- [x] continue the thing
- [ ] finish the thing

**Comment by TypeIsCheap** [comment]
@beauwoods what's the hosting situation for the website? i.e. how will I eventually "push to prod"?

**Comment by beauwoods** [comment]
The site runs on GitHub Pages, so when you push to the repo it goes live.

**Comment by TypeIsCheap** [comment]
Current direction is to adopt GatsbyJS as the site generator and information architecture.

**Comment by TypeIsCheap** [comment]
A few GatsbyJS starters that I liked:

https://www.gatsbyjs.com/starters/TryGhost/gatsby-starter-ghost/ 
https://www.gatsbyjs.com/starters/scttcper/gatsby-casper/
https://www.gatsbyjs.com/starters/codebushi/gatsby-starter-forty 
https://www.gatsbyjs.com/starters/WebCu/gatsby-material-kit-react

**Comment by TypeIsCheap** [comment]
@its-a-lisa and @beauwoods, I had some time to pull some of the existing content and some new free pictures into a theme that Iike. Many of the links are still placeholders but let me know if this visual theme is ok and I can start building out the sub pages:

It's on one of my domains here for now:  http://cone-designs.com/

**Comment by TypeIsCheap** [comment]
Uploaded Gatsby source tree to new repo here: https://github.com/SupplyChainSandbox/website-update feel free to edit and push commits as needed. I can rebuild the site and upload to the demo site as needed. Alternately we could commit the public folder after build once we get a bit further along. @its-a-lisa @beauwoods 

I think we can close this ticket.
